package dev.x2c.compiler.resource;

/** Small deterministic writer for generated Java source. */
final class JavaSource {
    private final StringBuilder value = new StringBuilder();
    private int indentation;

    JavaSource(String packageName, String typeName) {
        line("package " + packageName + ";");
        blank();
        line("// Generated by X2C. Do not edit.");
    }

    void line(String line) {
        for (int index = 0; index < indentation; index++) {
            value.append("    ");
        }
        value.append(line).append('\n');
    }

    void blank() {
        value.append('\n');
    }

    void open(String declaration) {
        line(declaration + " {");
        indent();
    }

    void close() {
        unindent();
        line("}");
    }

    void closeWith(String suffix) {
        unindent();
        line("}" + suffix);
    }

    void indent() {
        indentation++;
    }

    void unindent() {
        indentation--;
    }

    @Override
    public String toString() {
        return value.toString();
    }
}
