package dev.x2c.plugin.api;

import android.app.Activity;

/** Implemented by generated bytecode; Activity creation uses direct {@code new}, not reflection. */
public interface PluginActivityRegistry {
    /** Host/plugin component protocol version. */
    int CURRENT_RUNTIME_ABI = 1;

    int runtimeAbiVersion();

    String pluginId();

    boolean contains(String className);

    PluginActivityInfo info(String className);

    Activity create(String className);
}
